databases:
  - name: CyberLock
    plan: free
    databaseName: cyberlock
    user: cyberlock_user

services:
  - type: web
    name: my-app-name
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cyberlock_user
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
